LANGUAGES = {
    "en": "🇺🇸 English",
    "es": "🇪🇸 Spanish",
    "fr": "🇫🇷 French",
    "de": "🇩🇪 German",
    "it": "🇮🇹 Italian",
    "pt": "🇵🇹 Portuguese",
    "ru": "🇷🇺 Russian",
    "ja": "🇯🇵 Japanese",
    "ko": "🇰🇷 Korean",
    "zh": "🇨🇳 Chinese",
    "ar": "🇸🇦 Arabic",
    "hi": "🇮🇳 Hindi",
    "tr": "🇹🇷 Turkish",
    "nl": "🇳🇱 Dutch",
    "pl": "🇵🇱 Polish",
}
